version: '3'
silent: true
tasks:
  build:
    desc: "🏗️ Generate C shared library, dependencies and executable"
    cmds:
      - test -d native_code/build || mkdir -p native_code/build
      - cd native_code/build && cmake .. && cmake --build . && make

  ffigen:
    desc: "⚙️ Generate dart code with ffigen from C lang"
    cmds:
      - flutter pub run ffigen

  generate:
    desc: "️⛓️ Generate dependencies and bindings"
    cmds:
      - dart pub get
      - task build
      - task ffigen

  execute:
    desc: "🚀 Run Dart app without generate dependencies and bindings"
    cmds:
      - dart run bin/ffi_example.dart

  run:
    desc: "🚀 Build dependencies and run Dart app"
    cmds:
      - task generate
      - task execute

  default:
    cmds:
      - task -l --sort none